name: Build and Deploy NuGet Packages

on:
  push:
    branches: [ main ]
  # You can also trigger on other events such as pull_request, release, etc.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # specify your .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    # Optionally add test steps here

    - name: Pack
      run: dotnet pack --no-build -o nupkgs

#    - name: Push to NuGet
#      run: dotnet nuget push ./nupkgs/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
